"""
Test Generation Module

Generates unit tests from rubric criteria. Each criterion becomes one or more
test cases that verify the pass condition is met.

Supports:
- Python (pytest)
- TypeScript/JavaScript (Jest, Vitest)
- Go (testing package)
"""

import json
import re
from dataclasses import dataclass
from typing import Optional
from anthropic import Anthropic

# ============================================================================
# Data Models
# ============================================================================

@dataclass
class GeneratedTest:
    """A generated test case."""
    criterion_id: str
    test_name: str
    test_code: str
    language: str
    framework: str
    description: str

@dataclass
class TestSuite:
    """Collection of generated tests."""
    tests: list[GeneratedTest]
    setup_code: str
    imports: str
    language: str
    framework: str


# ============================================================================
# Test Templates
# ============================================================================

PYTEST_TEMPLATE = '''
"""
Auto-generated tests from rubric criteria.
Generated by Rubric Loop Test Generator.
"""

{imports}

{setup}

{tests}
'''

JEST_TEMPLATE = '''
/**
 * Auto-generated tests from rubric criteria.
 * Generated by Rubric Loop Test Generator.
 */

{imports}

{setup}

{tests}
'''

VITEST_TEMPLATE = JEST_TEMPLATE  # Same structure

GO_TEMPLATE = '''
// Auto-generated tests from rubric criteria.
// Generated by Rubric Loop Test Generator.

package {package}

{imports}

{tests}
'''


# ============================================================================
# Test Generator
# ============================================================================

class TestGenerator:
    """Generates tests from rubric criteria."""
    
    def __init__(self, model: str = "claude-sonnet-4-20250514"):
        self.client = Anthropic()
        self.model = model
    
    def generate_tests(
        self,
        code: str,
        rubric: dict,
        language: str = "python",
        framework: str = None
    ) -> TestSuite:
        """Generate test suite from rubric criteria."""
        
        # Determine framework
        if framework is None:
            framework = self._default_framework(language)
        
        # Generate tests for each criterion
        tests = []
        for criterion in rubric.get('criteria', []):
            test = self._generate_test_for_criterion(
                code=code,
                criterion=criterion,
                language=language,
                framework=framework
            )
            if test:
                tests.append(test)
        
        # Generate setup code
        setup = self._generate_setup(code, language, framework)
        imports = self._generate_imports(tests, language, framework)
        
        return TestSuite(
            tests=tests,
            setup_code=setup,
            imports=imports,
            language=language,
            framework=framework
        )
    
    def _default_framework(self, language: str) -> str:
        """Get default test framework for language."""
        defaults = {
            "python": "pytest",
            "typescript": "vitest",
            "javascript": "jest",
            "go": "testing"
        }
        return defaults.get(language, "pytest")
    
    def _generate_test_for_criterion(
        self,
        code: str,
        criterion: dict,
        language: str,
        framework: str
    ) -> Optional[GeneratedTest]:
        """Generate test(s) for a single criterion."""
        
        prompt = f"""Generate a test for this criterion:

CRITERION:
- ID: {criterion.get('id')}
- Description: {criterion.get('description')}
- Pass Condition: {criterion.get('pass_condition')}
- Category: {criterion.get('category', 'functionality')}

CODE TO TEST:
```{language}
{code}
```

REQUIREMENTS:
- Language: {language}
- Framework: {framework}
- Write ONE focused test function that verifies the criterion's pass condition
- Include descriptive test name and docstring
- Handle edge cases mentioned in the pass condition
- Mock external dependencies if needed

OUTPUT FORMAT:
Output ONLY the test function code, no imports or setup.
Use this naming convention: test_{criterion.get('id')}_{brief_description}
"""
        
        response = self.client.messages.create(
            model=self.model,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}]
        )
        
        test_code = self._extract_code(response.content[0].text, language)
        test_name = self._extract_test_name(test_code, language)
        
        return GeneratedTest(
            criterion_id=criterion.get('id'),
            test_name=test_name,
            test_code=test_code,
            language=language,
            framework=framework,
            description=criterion.get('description', '')
        )
    
    def _generate_setup(self, code: str, language: str, framework: str) -> str:
        """Generate test setup/fixtures."""
        
        prompt = f"""Generate test setup code for testing this module:

CODE:
```{language}
{code[:2000]}  # Truncated for prompt
```

REQUIREMENTS:
- Language: {language}
- Framework: {framework}
- Create any necessary fixtures, mocks, or setup functions
- Include database mocks, API mocks, etc. if the code uses them
- Keep it minimal - only what's needed

OUTPUT FORMAT:
Output ONLY the setup code (fixtures, beforeEach, etc.)
"""
        
        response = self.client.messages.create(
            model=self.model,
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}]
        )
        
        return self._extract_code(response.content[0].text, language)
    
    def _generate_imports(
        self,
        tests: list[GeneratedTest],
        language: str,
        framework: str
    ) -> str:
        """Generate import statements."""
        
        if language == "python" and framework == "pytest":
            return """import pytest
from unittest.mock import Mock, patch, MagicMock
"""
        
        elif language in ("typescript", "javascript") and framework in ("jest", "vitest"):
            if framework == "vitest":
                return """import { describe, it, expect, beforeEach, vi } from 'vitest';
"""
            else:
                return """import { describe, it, expect, beforeEach } from '@jest/globals';
"""
        
        elif language == "go":
            return """import (
    "testing"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/mock"
)
"""
        
        return ""
    
    def _extract_code(self, text: str, language: str) -> str:
        """Extract code from response."""
        # Find code block
        pattern = rf'```(?:{language})?\s*([\s\S]*?)\s*```'
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return text.strip()
    
    def _extract_test_name(self, code: str, language: str) -> str:
        """Extract test function name from code."""
        if language == "python":
            match = re.search(r'def (test_\w+)', code)
        elif language in ("typescript", "javascript"):
            match = re.search(r'(?:it|test)\(["\']([^"\']+)', code)
        elif language == "go":
            match = re.search(r'func (Test\w+)', code)
        else:
            match = None
        
        return match.group(1) if match else "unknown_test"
    
    def format_test_suite(self, suite: TestSuite) -> str:
        """Format test suite as a complete file."""
        
        tests_code = "\n\n".join(test.test_code for test in suite.tests)
        
        if suite.language == "python":
            template = PYTEST_TEMPLATE
        elif suite.language in ("typescript", "javascript"):
            template = JEST_TEMPLATE
        elif suite.language == "go":
            template = GO_TEMPLATE
        else:
            template = "{imports}\n\n{setup}\n\n{tests}"
        
        return template.format(
            imports=suite.imports,
            setup=suite.setup_code,
            tests=tests_code,
            package="main"  # For Go
        )
    
    def generate_test_file(
        self,
        code: str,
        rubric: dict,
        output_path: str,
        language: str = None,
        framework: str = None
    ) -> str:
        """Generate and save a complete test file."""
        
        # Infer language from output path if not specified
        if language is None:
            if output_path.endswith('.py'):
                language = "python"
            elif output_path.endswith('.ts'):
                language = "typescript"
            elif output_path.endswith('.js'):
                language = "javascript"
            elif output_path.endswith('_test.go'):
                language = "go"
            else:
                language = "python"
        
        suite = self.generate_tests(code, rubric, language, framework)
        content = self.format_test_suite(suite)
        
        with open(output_path, 'w') as f:
            f.write(content)
        
        return output_path


# ============================================================================
# Criterion-to-Test Mapping Examples
# ============================================================================

"""
Examples of how criteria map to tests:

CRITERION: api_validation
Description: Validates all input before processing
Pass Condition: Request body validated against schema, returns 400 with field-level errors

GENERATED TEST (pytest):
```python
def test_api_validation_rejects_invalid_email():
    '''Validates that invalid email format returns 400 with field error.'''
    response = client.post('/users', json={
        'email': 'not-an-email',
        'name': 'Test User'
    })
    
    assert response.status_code == 400
    assert 'email' in response.json()['errors']

def test_api_validation_rejects_missing_required_field():
    '''Validates that missing required field returns 400.'''
    response = client.post('/users', json={
        'name': 'Test User'
        # missing email
    })
    
    assert response.status_code == 400
    assert 'email' in response.json()['errors']
```

---

CRITERION: auth_pkce
Description: PKCE implemented correctly
Pass Condition: Code verifier crypto-random 43-128 chars, challenge is SHA256 base64url

GENERATED TEST (jest):
```javascript
describe('PKCE implementation', () => {
    it('generates verifier with correct length', () => {
        const verifier = generateCodeVerifier();
        expect(verifier.length).toBeGreaterThanOrEqual(43);
        expect(verifier.length).toBeLessThanOrEqual(128);
    });
    
    it('generates cryptographically random verifier', () => {
        const v1 = generateCodeVerifier();
        const v2 = generateCodeVerifier();
        expect(v1).not.toBe(v2);
    });
    
    it('creates S256 challenge from verifier', () => {
        const verifier = 'test-verifier-string-that-is-long-enough-43chars';
        const challenge = generateCodeChallenge(verifier);
        
        // Verify it's base64url encoded (no +, /, =)
        expect(challenge).not.toMatch(/[+/=]/);
        
        // Verify it's the right length for SHA256 base64
        expect(challenge.length).toBe(43);
    });
});
```

---

CRITERION: db_idempotent
Description: Migration is idempotent
Pass Condition: IF NOT EXISTS for creates, safe to run multiple times

GENERATED TEST (pytest):
```python
def test_migration_idempotent():
    '''Running migration twice should not raise errors.'''
    # Run migration first time
    run_migration('up')
    
    # Run migration second time - should not fail
    run_migration('up')
    
    # Verify table exists and has expected structure
    assert table_exists('users')
    assert column_exists('users', 'role')
```
"""


# ============================================================================
# CLI Interface
# ============================================================================

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate tests from rubric criteria")
    parser.add_argument("code_file", help="File containing code to test")
    parser.add_argument("rubric_file", help="JSON file containing rubric")
    parser.add_argument("--output", "-o", help="Output test file path")
    parser.add_argument("--language", "-l", help="Target language")
    parser.add_argument("--framework", "-f", help="Test framework")
    
    args = parser.parse_args()
    
    # Load inputs
    with open(args.code_file) as f:
        code = f.read()
    
    with open(args.rubric_file) as f:
        rubric = json.load(f)
    
    # Determine output path
    output = args.output
    if not output:
        base = args.code_file.rsplit('.', 1)[0]
        ext = args.code_file.rsplit('.', 1)[1] if '.' in args.code_file else 'py'
        if ext == 'py':
            output = f"{base}_test.py"
        elif ext in ('ts', 'tsx'):
            output = f"{base}.test.ts"
        elif ext in ('js', 'jsx'):
            output = f"{base}.test.js"
        elif ext == 'go':
            output = f"{base}_test.go"
        else:
            output = f"{base}_test.py"
    
    # Generate tests
    generator = TestGenerator()
    path = generator.generate_test_file(
        code=code,
        rubric=rubric,
        output_path=output,
        language=args.language,
        framework=args.framework
    )
    
    print(f"Generated test file: {path}")
    
    # Show summary
    with open(path) as f:
        content = f.read()
    
    test_count = content.count('def test_') + content.count('it(') + content.count('func Test')
    print(f"Generated {test_count} test(s) from {len(rubric.get('criteria', []))} criteria")


if __name__ == "__main__":
    main()
